### ISSUE TITLE
Rendering in testapp is "interesting"

### ISSUE THREAD

**Issue by pwaller** [haiyamicode/gosgl#3]
The rendering is frequently correct, but running the program repeatedly, I get something which looks like this:

![screenshot from 2014-05-05 11 44 16](https://cloud.githubusercontent.com/assets/438648/2877121/e7bf060a-d443-11e3-9ba6-6791664ac61e.png)

**Comment by haiyamicode** [comment]
Oh strange, I tried running again and again a lot of times on my machine and still don't get that result. I'll try updating go-gl to the latest version to see if there's any difference.

**Comment by pwaller** [comment]
This might be one of those things which is not easy to track down without access to a machine which can reproduce it, and I don't have tons of time to investigate it.

One possible problem is that the screen is only rendered once, and not after a viewport change event.

I recommend closing this issue unless you want to try making changes which I can test on my side.

```
$ apt-cache policy libglfw3
libglfw3:
  Installed: 3.0.4-1
  Candidate: 3.0.4-1
  Version table:
 *** 3.0.4-1 0
        100 /var/lib/dpkg/status
$ apt-cache policy libglew-dev
libglew-dev:
  Installed: 1.10.0-3
  Candidate: 1.10.0-3
  Version table:
 *** 1.10.0-3 0
        500 http://gb.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by haiyamicode** [comment]
@pwaller I moved the render to the loop and found critical bugs. All fixed now, rendering in the loop is working, #3 should never happen again.
Thanks a lot for the report.
Btw, are you interested in participating?

**Comment by pwaller** [comment]
Hi @phaikawl, it looks like a cool project something I have needed in the past and might need in the future. I don't really have any more resources than I've just given at the moment.

I can't test right now as I'm not at the computer I tested before.

However, we're always looking for contributors to go-gl if you would like to join our organization. The main benefit is that there are a few of us over there with the ability to merge pull requests and add new maintainers, and so projects don't die forever should the maintainer of an individual project become unavailable.

Btw, what does "gosgl" mean? :)

**Comment by haiyamicode** [comment]
@pwaller it means go's gl, god's gl, go super gl or whatever one may interpret ;)
I think it's fine for the project to be here currently, it may join the organization at some point, I don't know, but thanks for the invitation anyway.
Good to hear you like it, sadly looks like i gotta continue the lone development, I can see that you're quite busy with other projects already. Btw, do you know of anyone over go-gl could be interested in this and got time?

**Comment by pwaller** [comment]
@phaikawl you might shoot a message to go-gl@googlegroups.com.

If you change your mind you're welcome to join us as a joint owner of the go-gl organization.

I'd recommend calling the package something which makes it more obvious what it does. Currently that is something to do with vector graphics rendering in OpenGL, which is really cool, and worth advertising to the world. I almost didn't spot it.

Cheers,

Peter

**Comment by haiyamicode** [comment]
I thought about a name like <something>vg, but haven't found one that doesn't suck ==".

**Comment by pwaller** [comment]
Fair point. `vg` isn't so bad, especially if accompanied by a description. Some more ideas: `vectorgl` `pathgl` `beziergl` `curvegl`. Or if you lived in the `go-gl` namespace you could drop `gl`.

**Comment by haiyamicode** [comment]
@pwaller well those names are too generic dude :v

**Comment by pwaller** [comment]
@phaikawl well, what are you trying to achieve? I would make a package which does one thing and does it well, and has an obvious name so that people can find it. If you make something called "godgl" and put the kitchen sink in it, it's harder for people to find and use it. That's just my 2c, though, and I could equally well be wrong. I wish you luck in whatever case! :smiley:

**Comment by haiyamicode** [comment]
@pwaller I like unique names though ^^, overly generic names don't sound good to me.
